# Generated by Django 2.1.2 on 2019-03-05 04:02

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin',
            field=models.ImageField(height_field=64, upload_to=authentication.models.skin_upload_to, width_field=64),
        ),
    ]
