# Generated by Django 2.1.2 on 2019-03-05 05:46

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190305_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cloak',
            field=models.ImageField(default=1, upload_to=authentication.models.skin_upload_to),
            preserve_default=False,
        ),
    ]
